# Generated by Django 3.0.3 on 2020-02-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('comment_date', models.DateTimeField(verbose_name='date_commented')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Article')),
            ],
        ),
    ]
